### ISSUE TITLE
Unable to theme textfield label/placeholder

### ISSUE THREAD

**Issue by deilv** [jamesmfriedman/rmwc#276]
### What RMWC Version are you using?

1.8.3

### What browser(s) and React Version is this bug affecting?

Safari, Firefox, Chrome
React 16.4.1

### What build system are you using?

Webpack

### What are the steps to reproduce the bug?

Create a Textfield with a label or placeholder and try to change primary color using ThemeProvider.
Example: https://codesandbox.io/s/pp65870mw7

### What is the expected behavior?

Changing primary color should (?) also apply to label/placeholder text or at least a separate attribute should be available like there is for changing hint text.

### What is the actual behavior?

Label/placeholder does not change.

### Any other information you believe would be useful?

I'm not quite sure this is an issue of rmwc, it may as well be a bug of material-components-web or I may be missing something.

**Comment by Deilv** [comment]
This issue is also visible in the [textfield examples page](https://jamesmfriedman.github.io/rmwc/text-fields). Change the theme from the menu on the top-right and see the issue reproduce by clicking on a textfield.

**Comment by Deilv** [comment]
Thanks a lot for your reply and workaround:)

**Comment by loicnestler** [comment]
Hey! Any updates on that issue?

**Comment by jamesmfriedman** [comment]
Jumping through a bunch or random issues brought me to this one which seems to be the main issue. https://github.com/material-components/material-components-web/issues/4709

The MDC team hears from me often enough about my love of runtime CSS vars. I’d say commenting there or opening an additional issue would show some support.

For my projects I generally just maintain a file of those fixes. I’ve been hesitant to add one directly to MDC since the rules can get kind of crazy to fix it but it’s something I can consider.

**Comment by jamesmfriedman** [comment]
After many years of dealing with these types issues, I've added a theme fixes file directly to RMWC that takes care of these little issues since I've had a hard time getting them fixed upstream. Will be out with V6.

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0.

**Comment by b-d-m-p** [comment]
@jamesmfriedman Still getting this issue in 6.1.4. Maybe I don't understand the explanation on this page clearly. https://rmwc.io/theme You say to "include both", but I am not sure where or what the theme file is. Can you make it more explicit or give an example?

**Comment by kale1d0code** [comment]
I can confirm this is still broken in 6.1.4
applying the aforementioned style fix also brakes error colour (is primary colour instead of red)
