### ISSUE TITLE
Controlled tabs are not working as expected

### ISSUE THREAD

**Issue by akobylianskyi** [jamesmfriedman/rmwc#383]
RMWC version **4.0.1**
Codesandbox: https://codesandbox.io/s/yr468rnrx

Simple example:
```
import React from "react";
import ReactDOM from "react-dom";
import { TabBar, Tab } from "@rmwc/tabs";

import "@material/tab-bar/dist/mdc.tab-bar.css";
import "@material/tab/dist/mdc.tab.css";
import "@material/tab-scroller/dist/mdc.tab-scroller.css";
import "@material/tab-indicator/dist/mdc.tab-indicator.css";

function App() {
  return (
    <TabBar activeTabIndex={0}>
      <Tab>Cookies</Tab>
      <Tab>Pizza</Tab>
      <Tab>Icecream</Tab>
    </TabBar>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

Try to change the active tab.

**Actual behavior:**
It's possible to change the active tab even when **activeTabIndex** was passed to the **TabBar** component.

**Expected behavior:**
A user should not be able to change tab if **activeTabIndex** property was not changed.

**Comment by jamesmfriedman** [comment]
Thank you for reporting. You are absolutely correct, this appears to be a regression from previous behavior. Digging in, activeTabIndex is only respected initially.

The library is getting updated to MDC 0.42.0 next week, I'll make sure this makes it into the next release.

**Comment by jamesmfriedman** [comment]
Fixed with the release of V5

**Comment by akobylianskyi** [comment]
@jamesmfriedman That bug is still reproducible with the 5.1.7 version. Codesandbox: https://codesandbox.io/s/j4vk13knnw

**Comment by jamesmfriedman** [comment]
Thanks, will look back into it. There are tests around this, so it appears the test isn't asserting what it should.

**Comment by jamesmfriedman** [comment]
This has been officially fixed, hopefully once and for all. It was a rather complex issue in the end, but will go out in the next release.

**Comment by jamesmfriedman** [comment]
Fixed in the 5.2.0-alpha.0
