### ISSUE TITLE
SimpleMenu breaks when adding "renderToPortal" prop

### ISSUE THREAD

**Issue by anthonysapien** [jamesmfriedman/rmwc#627]
Here's a sandbox:
https://codesandbox.io/s/rmwc-sandbox-ybu69?file=/index.js

- What RMWC Version are you using [major.minor.patch]:
6.1.0

- Name your build system [Webpack, Rollup...]:
create-react-app

- Describe the bug with as much detail as possible:
Adding the renderToPortal prop to SimpleMenu causes the menu to no longer handle menu item selection.

- What happened, and what was supposed to happen:
When I add the renderToPortal property, if I open the SimpleMenu and click a menu item, the menu stays open and the onSelect event handler does not fire.

I expect the menu to close and the onSelect event handle to fire.

Thanks!

**Comment by anthonysapien** [comment]
I just tested the standard Menu, and it has the same issue. The renderToPortal Menu does not handle selection here: https://rmwc.io/menus

**Comment by mockingbird87** [comment]
Can confirm, I'm running into this issue as well!!

See my response[ here](https://github.com/jamesmfriedman/rmwc/issues/613#issuecomment-626207976) for a workaround.

**Comment by jamesmfriedman** [comment]
Confirming this is fixed in 6.1.2. You can try adding it in the docs to see. https://rmwc.io/menus

**Comment by anthonysapien** [comment]
Thanks for looking into it. I'm still seeing the issue on the RMWC site:
https://share.getcloudapp.com/4guj7d8N

The problem is that selecting an item doesn't close the menu.

**Comment by jamesmfriedman** [comment]
That specific example the open prop is always set to true. Just add `renderToPortal` to any others, it works as expected

**Comment by anthonysapien** [comment]
Apologies if I'm missing something. Here's a sandbox where I still don't see the menu close or the onSelect handler fire when I select an item:
https://codesandbox.io/s/rmwc-sandbox-fskbn

**Comment by jamesmfriedman** [comment]
@anthonysapien thanks for reporting that. I think it has to do with event bubbling through React portals and the fact that MDC doesn't use react events, but standard DOM ones. I'll have to inspect more.

For now, here is a non-ideal, but working solution. https://codesandbox.io/s/rmwc-sandbox-omw4n

**Comment by anthonysapien** [comment]
Cool @jamesmfriedman. Thanks for looking into it and for the workaround.

**Comment by rayjd** [comment]
This also affects the select menu if the enhanced prop is used. And unfortunately the workaround does not work because there aren't props to control the open state of the select menu.

To reproduce I just added the renderToPortal prop to the enhanced example: https://rmwc.io/select-menus

Hopefully the fix works for select menu too :)
